site_name: markhj/text
theme:
  name: material
nav:
  - 'Home': 'index.md'
  - 'Basics':
    - 'Getting started': 'text/basics.md'
    - 'Text from file': 'text/textfromfile.md'
    - 'Revise': 'text/decoration.md'
    - 'Getters': 'text/getters.md'
  - 'Data':
    - 'Basics': 'data/data.md'
    - 'Data maps': 'data/datamaps.md'
    - 'Repository': 'text/repository.md'
    - 'Namespaces': 'data/namespaces.md'
    - 'Static maps': 'data/static-datamaps.md'
    - 'Global maps': 'data/global-datamaps.md'
  - 'Parsers':
    - 'Basics': 'text/parserbasics.md'
    - 'Native parsers': 'parsers/native-parsers.md'
    - 'Parser class': 'parsers/custom-parser.md'
    - 'Global parsers': 'parsers/global-parser.md'
  - 'Iterators':
    - 'ForEach': 'iterators/foreach.md'
    - 'Map': 'iterators/map.md'
    - 'Rebase': 'iterators/rebase.md'
    - 'Differences': 'iterators/differences.md'
  - 'Cursor':
    - 'Getting started': 'cursor/basics.md'
    - 'Navigation': 'cursor/navigation.md'
    - 'Selection': 'cursor/selection.md'
    - 'Manipulation': 'cursor/manipulation.md'
    - 'Slicing': 'cursor/slicing.md'
  - 'Advanced concepts':
      'Fragments': 'advanced/fragments.md'
      'Expression patterns':
        - 'Custom pattern': 'expression-patterns/custompattern.md'
        - 'Convert pattern': 'expression-patterns/convertpattern.md'
      'Encoding': 'advanced/encoding.md'